'use strict';
const $=id=>document.getElementById(id),KEY='momo-travel-v1',CATS=['항공권','숙박','교통','식사','간식 · 편의점','쇼핑','기타'],ICONS=['✈️','🛏️','🚆','🍽️','🍯','🛍️','•••'],UNITS={KRW:'원',JPY:'엔',CNY:'위안',USD:'달러',EUR:'유로',TWD:'대만달러',THB:'바트',VND:'동'};
const uid=()=>crypto.randomUUID(),num=v=>{const n=Number(String(v??'').replace(/[^\d.\-]/g,''));return Number.isFinite(n)?Math.abs(n):0},money=v=>Math.round(v).toLocaleString('ko-KR')+'원';
let db={trips:[]},active=null,pending=null,editId=null;
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v&&Array.isArray(v.trips))db=v;}catch(e){$('status').textContent='저장 자료를 읽지 못했습니다. 백업 파일로 복구해주세요.'}
function status(s){$('status').textContent=s}function current(){return db.trips.find(t=>t.id===active)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));if(window.TravelCloud?.enabled){TravelCloud.queue(current());return true}status('이 브라우저에 저장됨 · '+new Date().toLocaleTimeString('ko-KR'));return true}catch(e){status('저장 실패: 저장 공간이나 브라우저 설정을 확인하고 백업을 내려받아주세요.');return false}}
function blank(){return {id:uid(),destination:'',start:'',end:'',currency:'JPY',rate:null,entries:[],source:''}}
function krw(e,t){if(e.currency==='KRW')return e.amount;if(Number.isFinite(e.krw))return e.krw;return t.rate?Math.round(e.amount*t.rate):null}
function isSaleSelected(e){return e.saleSelected??!!e.sold}
function salePick(parent,e){let label=append(parent,'label','','sale-pick');let check=document.createElement('input');check.type='checkbox';check.checked=isSaleSelected(e);check.setAttribute('aria-label',(e.name||e.store)+' 판매 관리 선택');label.append(check,document.createTextNode(' 판매'));check.onchange=()=>{e.saleSelected=check.checked;persist();render()};return check}
function sums(t){let total=0,missing=0,recovery=0;for(const e of t.entries){let a=krw(e,t);if(a===null)missing++;else total+=a;for(const p of productRows(e))if(isSaleSelected(p)&&p.sold)recovery+=p.sale||0}return {total,recovery,missing}}
function append(parent,tag,text,cls){let el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el}
function date(v,year=new Date().getFullYear()){if(v instanceof Date&&!isNaN(v))return [v.getFullYear(),String(v.getMonth()+1).padStart(2,'0'),String(v.getDate()).padStart(2,'0')].join('-');if(typeof v==='number'&&window.XLSX){let d=XLSX.SSF.parse_date_code(v);return d?date(new Date(d.y,d.m-1,d.d)):''}let m=String(v??'').match(/(?:(\d{4})[.\-/년\s]+)?(\d{1,2})[.\-/월\s]+(\d{1,2})(?:일)?/);if(!m)return '';let y=+(m[1]||year),mo=+m[2],day=+m[3],d=new Date(y,mo-1,day);return d.getMonth()+1===mo&&d.getDate()===day?`${y}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`:''}
function duration(t){if(!t.start||!t.end)return '';let n=Math.round((Date.parse(t.end)-Date.parse(t.start))/86400000);return n>=0?(n===0?'당일':n+'박 '+(n+1)+'일')+' ':''}
function render(){let t=current();const openCats=new Set([...$('categories').querySelectorAll('details[open]')].map(d=>d.dataset.category));$('trips').replaceChildren();append($('trips'),'option','여행을 선택하세요').value='';for(const x of [...db.trips].sort((a,b)=>b.start.localeCompare(a.start))){let o=append($('trips'),'option',(x.start?Number(x.start.slice(5,7))+'월 ':'')+(x.destination||'여행지 미입력')+' 여행'+(x.start?' · '+x.start:''));o.value=x.id;o.selected=x.id===active}
$('categories').replaceChildren();$('shopping').replaceChildren();if(!t){$('title').textContent='우리의 여행 기록';$('dates').textContent='파일을 가져오거나 새 여행을 시작하세요.';for(const id of ['total','recovery','net'])$(id).textContent='0원';$('breakdown').textContent='';$('soldcount').textContent='판매 완료 0개';$('formula').textContent='총 지출비용 − 총 회수비용';append($('shopping'),'div','여행 파일을 가져오면 쇼핑 목록이 표시됩니다.','empty');return}
let s=sums(t);$('title').textContent=duration(t)+(t.destination||'여행지 미입력')+' 여행';$('dates').textContent=t.start&&t.end?t.start.replaceAll('-','.')+' ~ '+t.end.replaceAll('-','.'):'여행 날짜 확인 필요';$('total').textContent=s.missing?'환율 입력 필요':money(s.total);$('recovery').textContent=money(s.recovery);$('net').textContent=s.missing?'환율 입력 필요':money(s.total-s.recovery);$('formula').textContent=s.missing?'원화 환산되지 않은 내역 '+s.missing+'건':money(s.total)+' − '+money(s.recovery);$('soldcount').textContent='판매 완료 '+t.entries.filter(e=>e.category==='쇼핑').flatMap(productRows).filter(e=>isSaleSelected(e)&&e.sold).length+'개';let groups={};for(let e of t.entries){let c=e.currency;groups[c]??={amount:0,krw:0,missing:0};groups[c].amount+=e.amount;let a=krw(e,t);if(a===null)groups[c].missing++;else groups[c].krw+=a}
$('breakdown').textContent=Object.entries(groups).map(([c,g])=>c==='KRW'?'원화 지출 '+money(g.amount):(UNITS[c]||c)+' 지출 '+g.amount.toLocaleString('ko-KR')+(UNITS[c]||c)+' → '+(g.missing?'환율 확인 필요':money(g.krw))).join(' / ')+(t.currency!=='KRW'?' · 적용 환율: 1'+UNITS[t.currency]+' = '+(t.rate??'미입력')+'원':'');
CATS.forEach((cat,i)=>{let rows=t.entries.filter(e=>e.category===cat),d=document.createElement('details');d.className='cat';d.dataset.category=cat;d.open=openCats.has(cat);let summary=append(d,'summary','');append(summary,'span',ICONS[i]+' '+cat);append(summary,'span',rows.some(e=>krw(e,t)===null)?'환율 확인':money(rows.reduce((a,e)=>a+krw(e,t),0)));let ul=append(d,'ul','');if(!rows.length)append(ul,'li','내역 없음');for(let e of rows){let li=append(ul,'li',(e.date?Number(e.date.slice(5,7))+'.'+Number(e.date.slice(8)): '날짜 확인 필요')+' '+e.store+(e.name?' · '+e.name:'')+' · '+(krw(e,t)===null?'원화 환산 필요':money(krw(e,t)))+(e.currency==='KRW'?'':' ('+e.amount.toLocaleString('ko-KR')+UNITS[e.currency]+')'));if(cat==='쇼핑'){if(e.items?.length){let products=append(li,'ul','','shopping-products');for(const product of e.items){let item=append(products,'li',(product.name||product.store)+' · '+(krw(product,t)===null?'원화 환산 필요':money(krw(product,t)))+(product.currency==='KRW'?'':' ('+product.amount.toLocaleString('ko-KR')+UNITS[product.currency]+')'));salePick(item,product);let edit=append(item,'button','수정');edit.onclick=()=>openEntry(product)}}else salePick(li,e)}else if(e.details?.length){let detail=append(li,'ul','');for(const x of e.details)append(detail,'li',x.name+' · '+x.amount.toLocaleString('ko-KR')+UNITS[x.currency]);}let b=append(li,'button','수정');b.style.cssText='padding:2px 7px;margin-left:8px;font-size:11px';b.onclick=()=>openEntry(e)}$('categories').append(d)});
let shopping=t.entries.filter(e=>e.category==='쇼핑').flatMap(productRows).filter(isSaleSelected);if(!shopping.length)append($('shopping'),'div','쇼핑 상세내역에서 판매를 체크한 상품만 여기에 표시됩니다.','empty');for(let e of shopping){let row=append($('shopping'),'div','','shop'),desc=append(row,'div','');append(desc,'small',e.store);let name=append(desc,'button',e.name||e.store,'product-name');name.title='클릭해서 수정';name.onclick=()=>openEntry(e);append(row,'div','구매 '+(krw(e,t)===null?'환산 필요':money(krw(e,t))),'purchase');let sale=append(row,'div','','sale');let input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.placeholder='판매금액';input.value=e.sold?e.sale:'';input.setAttribute('aria-label','판매금액 원');sale.append(input);let button=append(sale,'button',e.sold?'판매 완료':'판매');button.disabled=!!e.sold;input.oninput=()=>{button.textContent='판매';button.disabled=false};button.onclick=()=>{if(input.value.trim()===''||!Number.isFinite(+input.value)||+input.value<0)return status('판매금액을 0 이상의 숫자로 입력해주세요.');e.sold=true;e.sale=Math.round(+input.value);persist();render()}}
}
function openMeta(){let t=current();if(!t){t=blank();db.trips.push(t);active=t.id}for(const k of ['destination','start','end','currency','rate'])$(k).value=t[k]??'';$('metadata').showModal()}
$('new').onclick=()=>{let t=blank();db.trips.push(t);active=t.id;render();openMeta()};$('edit').onclick=openMeta;$('trips').onchange=e=>{active=e.target.value;render()};$('save').onclick=()=>{if(!current())return status('먼저 여행을 만들어주세요.');persist()};$('metaform').onsubmit=e=>{e.preventDefault();if($('end').value<$('start').value)return status('종료일은 시작일 이후로 입력해주세요.');let t=current();for(let k of ['destination','start','end','currency'])t[k]=$(k).value;t.rate=+$('rate').value;$('metadata').close();persist();render()};
for(let c of CATS)append($('ecat'),'option',c).value=c;for(let [c,u]of Object.entries(UNITS))append($('ecurrency'),'option',u+' ('+c+')').value=c;
function openEntry(e){if(!current())return status('먼저 여행을 만들어주세요.');editId=e?.id||null;$('edate').value=e?.date||current().start;$('ecat').value=e?.category||'기타';$('estore').value=e?.store||'';$('ename').value=e?.name||'';$('eamount').value=e?.amount??'';$('ecurrency').value=e?.currency||current().currency;$('eqty').value=1;$('eqty').disabled=!!e;$('entry').showModal()}
$('add').onclick=()=>openEntry();$('entryform').onsubmit=ev=>{ev.preventDefault();let t=current(),e={date:$('edate').value,category:$('ecat').value,store:$('estore').value,name:$('ename').value,amount:+$('eamount').value,currency:$('ecurrency').value};if(editId){let old=t.entries.flatMap(x=>[x,...(x.items||[])]).find(x=>x.id===editId);const changed=old.amount!==e.amount||old.currency!==e.currency;let receipt=t.entries.find(x=>x.items?.some(p=>p.id===editId));if(receipt&&changed&&old.currency===e.currency){receipt.amount+=e.amount-old.amount;delete receipt.krw}Object.assign(old,e);if(changed)delete old.krw}else{let q=e.category==='쇼핑'?+$('eqty').value:1;for(let i=0;i<q;i++)t.entries.push({...e,id:uid(),amount:e.amount/q,sold:false,sale:0})}$('entry').close();persist();render()};
$('backup').onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='우리의-여행가계부-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function category(s){if(/면세|쇼핑|아울렛|시계|빅카메라|백화점|의류|신발/i.test(s))return '쇼핑';if(/항공|비행|항공권|airline/i.test(s))return '항공권';if(/숙박|호텔|hotel|숙소/i.test(s))return '숙박';if(/교통|택시|버스|지하철|기차|철도|전철/i.test(s))return '교통';if(/간식|편의점|커피|카페|과자/i.test(s))return '간식 · 편의점';if(/식사|식비|라멘|식당|음식|점심|저녁|아침|카레|텐푸라/i.test(s))return '식사';return '기타'}
function currency(s,fallback){if(/위안|CNY|RMB|元/i.test(s))return 'CNY';if(/엔|JPY|円/i.test(s))return 'JPY';if(/원|KRW|₩/i.test(s))return 'KRW';if(/달러|USD|\$/i.test(s))return 'USD';if(/유로|EUR|€/i.test(s))return 'EUR';return fallback}
function fromRows(rows,t){let h=rows.findIndex(r=>r.some(x=>/^(날짜|일자|거래일|date)$/i.test(String(x).trim()))&&r.some(x=>/금액|amount/i.test(String(x))));if(h<0)throw Error('날짜·금액 열을 찾지 못했습니다. 텍스트 파일로 내보내거나 지출을 직접 추가해주세요.');let heads=rows[h].map(x=>String(x).trim()),get=(r,re)=>r[heads.findIndex(x=>re.test(x))];for(let r of rows.slice(h+1)){let raw=get(r,/^(금액|지출금액|amount|현지금액)$/i);if(raw===undefined||raw===''||!/[0-9]/.test(String(raw)))continue;if(/수입|이체/.test(String(get(r,/타입|유형/))))continue;let store=String(get(r,/내용|매장|구매처|항목|상호|store/i)||''),cat=String(get(r,/카테고리|대분류|category/i)||''),q=Math.min(100,Math.max(1,Math.floor(num(get(r,/수량|quantity/i))||1))),cur=currency(String(get(r,/통화|currency/i)||raw),t.currency),name=String(get(r,/상품명|product/i)||''),converted=get(r,/원화.*금액|환산.*액|KRW금액/i),amount=num(raw);let c=CATS.includes(cat)?cat:category(cat+' '+store+' '+name);for(let i=0;i<(c==='쇼핑'?q:1);i++){let entry={id:uid(),date:date(get(r,/날짜|일자|거래일|date/i)),store:store||'항목 확인 필요',name,category:c,currency:cur,amount:amount/(c==='쇼핑'?q:1),sold:false,sale:0};if(converted!==undefined&&converted!=='')entry.krw=num(converted)/(c==='쇼핑'?q:1);t.entries.push(entry)}}}
$('file').onchange=async ev=>{let f=ev.target.files[0];if(!f)return;try{status('파일을 읽고 있습니다…');let t=blank(),text='',ext=f.name.split('.').pop().toLowerCase();t.source=f.name;if(!['sdocx','txt','csv','xlsx','xls','json','html','htm','pdf'].includes(ext))throw Error('삼성노트(.sdocx), PDF, 텍스트 또는 엑셀 파일을 선택해주세요.');if(ext==='json'){let parsed=JSON.parse(await f.text());if(!Array.isArray(parsed.trips))throw Error('여행가계부 백업 파일이 아닙니다.');for(let x of parsed.trips){if(!x||!Array.isArray(x.entries)||!UNITS[x.currency]||!x.entries.every(e=>UNITS[e.currency]&&CATS.includes(e.category)&&Number.isFinite(e.amount)&&e.amount>=0))throw Error('백업 데이터 형식을 확인해주세요.')}pending={restore:parsed};$('importnote').textContent='백업 여행 '+parsed.trips.length+'개를 가져옵니다. 같은 ID의 여행은 현재 브라우저 데이터와 합치지 않고 건너뜁니다.';$('previewrows').replaceChildren()}else{if(['xlsx','xls','csv'].includes(ext)){if(!window.XLSX)throw Error('엑셀 읽기 도구를 불러오지 못했습니다. 인터넷 연결을 확인해주세요.');let wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true}),rows=[];for(let n of wb.SheetNames)rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''}));text=f.name+' '+rows.flat().join(' ');infer(t,text);fromRows(rows,t)}else{if(ext==='sdocx'){text=await readSamsungNote(await f.arrayBuffer())}else if(ext==='pdf'){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';let pdf=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;for(let i=1;i<=pdf.numPages;i++){let items=(await(await pdf.getPage(i)).getTextContent()).items;let y=null;for(let item of items){if(y!==null&&Math.abs(item.transform[5]-y)>3)text+='\n';text+=item.str+' ';y=item.transform[5]}text+='\n'}}else{text=await f.text();if(['html','htm'].includes(ext))text=new DOMParser().parseFromString(text,'text/html').body.innerText}infer(t,f.name+' '+text);fromText(text,t)}infer(t,f.name+' '+text);if(!t.entries.length)throw Error('금액이 포함된 지출을 찾지 못했습니다. 금액이 입력된 삼성노트·텍스트·PDF·엑셀 파일인지 확인해주세요.');db.trips.push(t);active=t.id;persist();render();status('파일에서 '+t.entries.length+'건을 읽어 저장했습니다. 여행 정보나 상품을 클릭하면 수정할 수 있어요.');return;} $('preview').showModal();status('가져온 내역을 확인해주세요.');}catch(e){status('가져오기 실패: '+e.message)}finally{ev.target.value=''}};
$('cancelimport').onclick=()=>{pending=null;$('preview').close();status('가져오기를 취소했습니다.')};$('confirmimport').onclick=()=>{if(!pending)return;if(pending.restore){let ids=new Set(db.trips.map(t=>t.id));for(let t of pending.restore.trips)if(!ids.has(t.id)){db.trips.push(t);ids.add(t.id)}active=db.trips.at(-1)?.id||null}else{let ids=new Set([...$('previewrows').querySelectorAll('input:checked')].map(e=>e.dataset.id));pending.trip.entries=pending.trip.entries.filter(e=>ids.has(e.id));if(!pending.trip.entries.length)return status('저장할 내역을 하나 이상 선택해주세요.');db.trips.push(pending.trip);active=pending.trip.id}pending=null;$('preview').close();persist();render()};
const salesPanel=$('shopping').parentElement;const salesDetails=document.createElement('details');salesDetails.id='salesDetails';const salesSummary=document.createElement('summary');salesSummary.textContent='판매 관리';salesSummary.style.cssText='cursor:pointer;font-size:25px;font-weight:700;list-style:revert';const salesHeading=salesPanel.querySelector('h2');salesHeading.replaceWith(salesDetails);salesDetails.append(salesSummary);const salesHint=salesPanel.querySelector('.muted');salesHint.textContent='판매금액을 입력하고 판매를 누르면 바로 처리됩니다.';salesDetails.append(salesHint,$('shopping'));
active=db.trips.at(-1)?.id||null;render();
