'use strict';
// Google Apps Script HTML service uses the same travel UI with authenticated server calls.
window.TravelCloud={enabled:!!(window.google?.script?.run),ready:false,versions:new Map(),pending:new Map(),busy:false,paused:false};
const travelRPC=(method,...args)=>new Promise((resolve,reject)=>google.script.run.withSuccessHandler(resolve).withFailureHandler(reject)[method](...args));
TravelCloud.queue=function(trip){if(!this.enabled||!trip)return;this.pending.set(trip.id,JSON.parse(JSON.stringify(trip)));this.flush()};
TravelCloud.flush=async function(){if(!this.ready||this.busy||this.paused||!this.pending.size)return;this.busy=true;try{while(this.pending.size){const [id,trip]=this.pending.entries().next().value;this.pending.delete(id);status('Google에 저장 중…');try{let result=await travelRPC('saveTravel',trip,this.versions.get(id)||0);this.versions.set(id,result.version);status('Google 공동 저장 완료 · '+new Date().toLocaleTimeString('ko-KR'))}catch(e){if(!this.pending.has(id))this.pending.set(id,trip);this.paused=true;status('Google 저장 실패 · '+e.message);break}}}finally{this.busy=false}};
TravelCloud.load=async function(){if(this.busy)return status('Google 저장이 끝난 후 새로고침해주세요.');if(this.pending.size){if(!confirm('아직 Google에 저장되지 않은 변경이 있습니다. 내 변경을 이 브라우저에 백업하고 Google의 최신 내용을 불러올까요?'))return;localStorage.setItem(KEY+'-unsynced',JSON.stringify(db));}status('Google 여행 목록을 불러오는 중…');try{const response=await travelRPC('loadTravel');this.pending.clear();this.paused=false;this.versions=new Map(response.items.map(x=>[x.trip.id,x.version]));db={trips:response.items.map(x=>x.trip)};localStorage.setItem(KEY,JSON.stringify(db));if(!db.trips.some(x=>x.id===active))active=db.trips.at(-1)?.id||null;render();status('')}catch(e){status('Google 불러오기 실패 · '+e.message)}};
window.addEventListener('DOMContentLoaded',async()=>{
 if(!TravelCloud.enabled)return;
 const saveButton=$('save');saveButton.onclick=()=>{if(!current())return status('먼저 여행을 만들어주세요.');TravelCloud.paused=false;persist()};
 const controls=[...document.querySelectorAll('button,input,select')];controls.forEach(e=>e.disabled=true);
 try{const local=db.trips.slice(),response=await travelRPC('loadTravel');TravelCloud.versions=new Map(response.items.map(x=>[x.trip.id,x.version]));const existing=new Set(response.items.map(x=>x.trip.id));const unsaved=local.filter(x=>!existing.has(x.id));db={trips:[...response.items.map(x=>x.trip),...unsaved]};if(!db.trips.some(x=>x.id===active))active=db.trips.at(-1)?.id||null;localStorage.setItem(KEY,JSON.stringify(db));render();TravelCloud.ready=true;status('');for(const t of unsaved)TravelCloud.queue(t);controls.forEach(e=>e.disabled=false)}catch(e){status('Google 연결 실패 · '+e.message+' · 새로고침으로 다시 연결해주세요.')}
});
